en:
    login.page_header: 'Login'
    login.login_placeholder: 'E-mail address'
    login.password_placeholder: 'Password'
    login.login_button: 'Login'
    login.forgot_password: 'Forgot password?'
    login.go_to_register_page: 'Register new account'
    register.page_header: 'Register account'
    register.register_failed: 'Sorry! Your account has not been created'
    register.name_placeholder: 'Enter your full name'
    register.email_placeholder: 'Enter your e-mail address'
    register.password_placeholder: 'Choose a password'
    register.register_button: 'Register'
    register.go_to_login_page: 'Go to login page'
    nav.toggle: 'Toggle navigation'
    nav.profile_page: 'Profile'
    nav.logout: 'Logout'
    flashbox.close: 'Close'
    footer.created_by: 'Created by'
    profile.full_name: 'Full name'
    profile.email: 'E-mail address'
    profile.password: 'Password'
    profile.password_confirmation: 'Password confirmation'
    profile.save_button: 'Save'
    profile_update.header: 'Update your personal information'
    profile_update.name: 'First name'
    profile_update.surname: 'Second name'
    profile_update.email: 'E-mail'
    profile_update.password: 'New password'
    profile_update.password_confirm: 'Confirm new password'
    profile_update.save_button: 'Save'
    error.404_header: 'SORRY!'
    error.404_content: 'The page you’re looking for was not found.'
    error.500_header: 'SORRY!'
    error.500_content: 'Internal server error.'
    error.back_to_home: 'Back to home'
    maintenance.header: 'Maintenance'
    maintenance.subheader: 'Service is temporarily unavailable.'
    maintenance.content: 'We are currently working on deploying new features. We will be back soon :)'
    choosecluster.header: 'Choose cluster'
    dashboard.welcome_message: 'Good to see you'
