# TODO: translate Polish to English
en:
    nav.dashboard: 'Dashboard'
    nav.gallery: 'Gallery'
    nav.todo: 'Todo'
    nav.profile-page: 'Profile'
    nav.logout: 'Logout'
    nav.settings: 'Settings'
    login.login_placeholder: 'Email'
    login.password_placeholder: 'Password'
    login.go_to_register_page: 'Go to register page'
    register.name_placeholder: 'Name'
    register.email_placeholder: 'Email'
    register.cluster_placeholder: 'Cluster'
    register.password_placeholder: 'Password'
    register.go_to_login_page: 'Go to login page'
pl:
    nav.dashboard: 'Kokpit'
    nav.gallery: 'Galeria'
    nav.todo: 'Todo'
    nav.profile-page: 'Profil'
    nav.logout: 'Wyloguj'
    nav.settings: 'Ustawienia'
    login.login_placeholder: 'Email'
    login.password_placeholder: 'Hasło'
    login.go_to_register_page: 'Przejdź do strony logowania'
    register.name_placeholder: 'Nazwa'
    register.email_placeholder: 'Email'
    register.cluster_placeholder: 'Cluster'
    register.password_placeholder: 'Hasło'
    register.go_to_login_page: 'Przejdź do strony logowania'