# TODO: translate Polish to English
en:
    nav.dashboard: 'Dashboard'
    nav.gallery: 'Gallery'
    nav.todo: 'Todo'
    nav.profile-page: 'Profile'
    nav.logout: 'Logout'
    nav.settings: 'Settings'
pl:
    nav.dashboard: 'Kokpit'
    nav.gallery: 'Galeria'
    nav.todo: 'Todo'
    nav.profile-page: 'Profil'
    nav.logout: 'Wyloguj'
    nav.settings: 'Ustawienia'